import type { WelfareService, ServiceCategory } from '@/types';

export const welfareServices: WelfareService[] = [
  // 생활지원 (20개)
  {
    id: 'service-1',
    name: '긴급복지지원',
    category: '생활지원',
    subcategory: '긴급지원',
    description: '위기상황에 처한 저소득층에게 생계·의료·주거 지원 등 필요한 복지서비스를 신속하게 지원',
    benefits: '생계지원, 의료지원, 주거지원, 사회복지시설 이용 지원 등',
    amount: '생계지원 월 최대 162만원 (4인 기준), 의료지원 300만원 이내',
    eligibility: {
      incomeLevel: '기준 중위소득 75% 이하',
      otherRequirements: ['재산 대도시 2.4억원 이하', '금융재산 600만원 이하'],
    },
    applicationMethods: ['주민센터 방문', '129 전화'],
    requiredDocuments: ['신분증', '소득·재산 확인 서류', '위기상황 증빙 서류'],
    processingTime: '선지원 후심사 (위기상황 시 즉시 지원)',
    contactInfo: '보건복지콜센터 129',
    tags: ['긴급', '생계', '의료', '주거'],
    popularity: 95,
  },
  {
    id: 'service-2',
    name: '에너지바우처',
    category: '생활지원',
    subcategory: '에너지지원',
    description: '에너지 취약계층에게 전기, 가스, 지역난방 등 에너지 비용을 지원',
    benefits: '전기, 가스, 지역난방 등 에너지 비용 바우처 지급',
    amount: '가구원 수에 따라 연간 최대 52.8만원',
    eligibility: {
      incomeLevel: '기준 중위소득 40% 이하',
      otherRequirements: ['소득인정액 기준 중위소득 40% 이하인 수급자'],
    },
    applicationMethods: ['주민센터 방문', '온라인(복지로)'],
    requiredDocuments: ['신분증', '수급자 증명서류'],
    processingTime: '14일 이내',
    contactInfo: '에너지바우처 콜센터 1600-3190',
    tags: ['에너지', '난방', '전기', '가스'],
    popularity: 88,
  },
  {
    id: 'service-3',
    name: '기초생활보장(생계급여)',
    category: '생활지원',
    subcategory: '기초보장',
    description: '기본적인 생활이 어려운 저소득층에게 생계급여를 지원',
    benefits: '생활에 필요한 급여 지급',
    amount: '기준 중위소득 32% - 가구 소득인정액',
    eligibility: {
      incomeLevel: '기준 중위소득 32% 이하',
      otherRequirements: ['부양의무자 기준 충족'],
    },
    applicationMethods: ['주민센터 방문'],
    requiredDocuments: ['신분증', '소득·재산 신고서', '금융정보등제공동의서'],
    processingTime: '30일 이내',
    contactInfo: '주민센터 또는 복지로 129',
    tags: ['기초생활', '생계', '저소득'],
    popularity: 92,
  },
  {
    id: 'service-4',
    name: '차상위계층 지원',
    category: '생활지원',
    subcategory: '차상위지원',
    description: '기초수급자가 아닌 차상위계층에 대한 의료·자활 등 복지서비스 연계',
    benefits: '의료비 지원, 자활근로 연계, 통신비 감면 등',
    eligibility: {
      incomeLevel: '기준 중위소득 50% 이하',
    },
    applicationMethods: ['주민센터 방문'],
    requiredDocuments: ['신분증', '소득·재산 증빙서류'],
    processingTime: '30일 이내',
    contactInfo: '주민센터',
    tags: ['차상위', '의료', '자활'],
    popularity: 75,
  },
  {
    id: 'service-5',
    name: '긴급 생활안정자금 대출',
    category: '생활지원',
    subcategory: '대출지원',
    description: '저소득·저신용 근로자에게 생활안정자금을 저금리로 대출',
    benefits: '저금리 생활안정자금 대출',
    amount: '최대 1,500만원',
    eligibility: {
      incomeLevel: '연소득 3,500만원 이하',
      otherRequirements: ['신용등급 6등급 이하'],
    },
    applicationMethods: ['근로복지공단'],
    requiredDocuments: ['신분증', '소득증빙서류', '재직증명서'],
    processingTime: '7일 이내',
    contactInfo: '근로복지공단 1588-0075',
    tags: ['대출', '긴급', '생활'],
    popularity: 68,
  },
  {
    id: 'service-6',
    name: '자활근로',
    category: '생활지원',
    subcategory: '자활',
    description: '근로능력이 있는 저소득층에게 근로기회를 제공하여 자활 지원',
    benefits: '자활근로 참여를 통한 급여 지급',
    amount: '시간당 최저임금 이상',
    eligibility: {
      ageRange: { min: 18, max: 64 },
      incomeLevel: '기준 중위소득 50% 이하',
      otherRequirements: ['근로능력 있는 자'],
    },
    applicationMethods: ['지역자활센터', '주민센터'],
    requiredDocuments: ['신분증', '수급자 증명서류'],
    processingTime: '14일 이내',
    contactInfo: '지역자활센터',
    tags: ['자활', '근로', '일자리'],
    popularity: 65,
  },
  {
    id: 'service-7',
    name: '청년월세 특별지원',
    category: '생활지원',
    subcategory: '주거지원',
    description: '경제적으로 어려운 청년들의 주거비 부담 완화를 위한 월세 지원',
    benefits: '월세 지원',
    amount: '월 최대 20만원 (최대 12개월)',
    eligibility: {
      ageRange: { min: 19, max: 34 },
      incomeLevel: '기준 중위소득 60% 이하',
    },
    applicationMethods: ['온라인(복지로)', '주민센터'],
    requiredDocuments: ['신분증', '임대차계약서', '소득증빙서류'],
    processingTime: '30일 이내',
    contactInfo: '복지로 129',
    tags: ['청년', '월세', '주거'],
    popularity: 82,
  },
  {
    id: 'service-8',
    name: '한부모가족 지원',
    category: '생활지원',
    subcategory: '한부모지원',
    description: '저소득 한부모가족의 생활 안정과 자립 지원',
    benefits: '아동양육비, 추가아동양육비, 학용품비, 생활보조금 등',
    amount: '아동양육비 월 20만원',
    eligibility: {
      incomeLevel: '기준 중위소득 60% 이하',
      householdTypes: ['한부모'],
    },
    applicationMethods: ['주민센터 방문'],
    requiredDocuments: ['신분증', '가족관계증명서', '소득·재산 증빙'],
    processingTime: '30일 이내',
    contactInfo: '여성가족부 1644-6621',
    tags: ['한부모', '양육비', '가족'],
    popularity: 78,
  },
  {
    id: 'service-9',
    name: '통신비 감면',
    category: '생활지원',
    subcategory: '통신지원',
    description: '저소득층의 통신비 부담 완화를 위한 감면 지원',
    benefits: '이동전화 및 유선전화 요금 감면',
    amount: '월 최대 26,000원 감면',
    eligibility: {
      incomeLevel: '기초생활수급자, 차상위계층',
    },
    applicationMethods: ['통신사 고객센터', '온라인'],
    requiredDocuments: ['수급자 증명서류'],
    processingTime: '즉시',
    contactInfo: '각 통신사 고객센터',
    tags: ['통신', '감면', '휴대폰'],
    popularity: 70,
  },
  {
    id: 'service-10',
    name: '재난적 의료비 지원',
    category: '생활지원',
    subcategory: '의료비지원',
    description: '과도한 의료비로 경제적 어려움을 겪는 가구 지원',
    benefits: '입원·외래·처방조제비 중 본인부담금 지원',
    amount: '연간 최대 3,000만원',
    eligibility: {
      incomeLevel: '기준 중위소득 100% 이하',
      otherRequirements: ['의료비 본인부담금이 연소득 15% 초과'],
    },
    applicationMethods: ['국민건강보험공단'],
    requiredDocuments: ['신분증', '진료비 영수증', '소득증빙'],
    processingTime: '30일 이내',
    contactInfo: '국민건강보험공단 1577-1000',
    tags: ['의료비', '재난', '지원'],
    popularity: 72,
  },

  // 의료 (18개)
  {
    id: 'service-11',
    name: '의료급여',
    category: '의료',
    subcategory: '기초의료',
    description: '생활이 어려운 저소득층에게 의료서비스 지원',
    benefits: '진찰, 검사, 치료, 수술, 입원 등 의료서비스',
    eligibility: {
      incomeLevel: '기초생활수급자',
    },
    applicationMethods: ['주민센터 방문'],
    requiredDocuments: ['신분증', '수급자 증명'],
    processingTime: '30일 이내',
    contactInfo: '주민센터 또는 129',
    tags: ['의료', '기초', '저소득'],
    popularity: 90,
  },
  {
    id: 'service-12',
    name: '건강보험료 경감',
    category: '의료',
    subcategory: '보험료지원',
    description: '저소득층의 건강보험료 부담 완화',
    benefits: '건강보험료 최대 50% 경감',
    eligibility: {
      incomeLevel: '저소득 지역가입자',
    },
    applicationMethods: ['국민건강보험공단'],
    requiredDocuments: ['신분증', '소득증빙'],
    processingTime: '14일 이내',
    contactInfo: '건강보험공단 1577-1000',
    tags: ['건강보험', '경감', '보험료'],
    popularity: 85,
  },
  {
    id: 'service-13',
    name: '노인장기요양보험',
    category: '의료',
    subcategory: '장기요양',
    description: '고령이나 노인성 질병으로 일상생활이 어려운 노인에게 서비스 제공',
    benefits: '신체활동, 가사지원, 목욕, 간호 등 서비스',
    amount: '등급에 따라 월 최대 159만원',
    eligibility: {
      ageRange: { min: 65 },
      otherRequirements: ['장기요양등급 판정 (1~5등급)'],
    },
    applicationMethods: ['국민건강보험공단 지사'],
    requiredDocuments: ['장기요양인정신청서', '의사소견서', '신분증'],
    processingTime: '약 30일 (등급판정위원회 심의)',
    contactInfo: '건강보험공단 1577-1000',
    tags: ['노인', '장기요양', '돌봄'],
    popularity: 88,
  },
  {
    id: 'service-14',
    name: '장애인 의료비 지원',
    category: '의료',
    subcategory: '장애인의료',
    description: '저소득 장애인의 의료비 부담 경감',
    benefits: '의료비 본인부담금 지원',
    eligibility: {
      incomeLevel: '기초생활수급자·차상위계층',
      otherRequirements: ['등록 장애인'],
    },
    applicationMethods: ['주민센터 방문'],
    requiredDocuments: ['신분증', '장애인등록증', '수급자 증명'],
    processingTime: '14일 이내',
    contactInfo: '주민센터',
    tags: ['장애인', '의료비', '지원'],
    popularity: 75,
  },
  {
    id: 'service-15',
    name: '암환자 의료비 지원',
    category: '의료',
    subcategory: '암환자지원',
    description: '저소득 암환자의 의료비 부담 경감',
    benefits: '암 치료비 지원',
    amount: '연간 최대 300만원',
    eligibility: {
      incomeLevel: '기준 중위소득 120% 이하',
      otherRequirements: ['암 진단을 받은 자'],
    },
    applicationMethods: ['보건소'],
    requiredDocuments: ['암 진단서', '소득증빙', '신분증'],
    processingTime: '14일 이내',
    contactInfo: '관할 보건소',
    tags: ['암', '의료비', '치료'],
    popularity: 72,
  },
  {
    id: 'service-16',
    name: '정신건강 복지서비스',
    category: '의료',
    subcategory: '정신건강',
    description: '정신질환자 및 정신건강 취약계층 지원',
    benefits: '정신건강 상담, 재활 프로그램, 치료비 지원',
    eligibility: {
      otherRequirements: ['정신건강 문제가 있는 자'],
    },
    applicationMethods: ['정신건강복지센터'],
    requiredDocuments: ['신분증'],
    processingTime: '상시',
    contactInfo: '정신건강위기상담전화 1577-0199',
    tags: ['정신건강', '상담', '재활'],
    popularity: 65,
  },
  {
    id: 'service-17',
    name: '치매검진 및 치료관리',
    category: '의료',
    subcategory: '치매관리',
    description: '치매 조기발견 및 치료비 지원',
    benefits: '치매검진비, 치료비 지원',
    eligibility: {
      ageRange: { min: 60 },
    },
    applicationMethods: ['보건소', '치매안심센터'],
    requiredDocuments: ['신분증'],
    processingTime: '상시',
    contactInfo: '치매상담콜센터 1899-9988',
    tags: ['치매', '검진', '노인'],
    popularity: 70,
  },
  {
    id: 'service-18',
    name: '희귀질환자 의료비 지원',
    category: '의료',
    subcategory: '희귀질환',
    description: '희귀질환자의 의료비 부담 경감',
    benefits: '의료비 본인부담금 지원',
    amount: '연간 최대 2,000만원',
    eligibility: {
      incomeLevel: '기준 중위소득 120% 이하',
      otherRequirements: ['희귀질환 진단'],
    },
    applicationMethods: ['보건소'],
    requiredDocuments: ['진단서', '소득증빙', '신분증'],
    processingTime: '30일 이내',
    contactInfo: '보건소',
    tags: ['희귀질환', '의료비'],
    popularity: 60,
  },

  // 주거 (15개)
  {
    id: 'service-19',
    name: '주거급여',
    category: '주거',
    subcategory: '기초주거',
    description: '저소득층의 주거비 부담 완화를 위한 임차료 또는 수선유지비 지원',
    benefits: '임차료 지원 또는 주택 수선비 지원',
    amount: '서울 기준 월 최대 53만원',
    eligibility: {
      incomeLevel: '기준 중위소득 48% 이하',
    },
    applicationMethods: ['주민센터 방문'],
    requiredDocuments: ['신분증', '임대차계약서', '소득·재산 증빙'],
    processingTime: '30일 이내',
    contactInfo: '주거급여 콜센터 1600-0777',
    tags: ['주거', '임차료', '수선'],
    popularity: 85,
  },
  {
    id: 'service-20',
    name: '긴급주거지원',
    category: '주거',
    subcategory: '긴급지원',
    description: '주거를 상실하거나 상실할 우려가 있는 위기상황 가구 지원',
    benefits: '임시거처 제공 또는 임시거소 비용 지원',
    amount: '월 최대 66만원 (서울 기준)',
    eligibility: {
      incomeLevel: '기준 중위소득 75% 이하',
      otherRequirements: ['주거 위기상황'],
    },
    applicationMethods: ['주민센터', '129'],
    requiredDocuments: ['신분증', '위기상황 증빙'],
    processingTime: '즉시',
    contactInfo: '129',
    tags: ['긴급', '주거', '임시'],
    popularity: 78,
  },
  {
    id: 'service-21',
    name: '공공임대주택',
    category: '주거',
    subcategory: '임대주택',
    description: '저소득층에게 시세보다 저렴한 공공임대주택 제공',
    benefits: '시세의 30~80% 수준 임대료로 주거 제공',
    eligibility: {
      incomeLevel: '기준 중위소득 70% 이하 (유형별 상이)',
    },
    applicationMethods: ['LH 청약센터', '지자체'],
    requiredDocuments: ['신분증', '소득증빙', '주민등록등본'],
    processingTime: '공고 시 신청',
    contactInfo: 'LH 1600-1004',
    tags: ['임대주택', '공공', 'LH'],
    popularity: 90,
  },
  {
    id: 'service-22',
    name: '주택 긴급수선',
    category: '주거',
    subcategory: '주택수선',
    description: '저소득 가구의 노후·불량 주택 긴급수선 지원',
    benefits: '주택 수선 비용 지원',
    amount: '최대 950만원',
    eligibility: {
      incomeLevel: '기초생활수급자, 차상위계층',
      otherRequirements: ['노후·불량 주택 거주'],
    },
    applicationMethods: ['주민센터', 'LH'],
    requiredDocuments: ['신분증', '수급자 증명', '주택 상태 확인서'],
    processingTime: '30일 이내',
    contactInfo: 'LH 1600-1004',
    tags: ['수선', '노후주택', '긴급'],
    popularity: 72,
  },
  {
    id: 'service-23',
    name: '전세자금 대출',
    category: '주거',
    subcategory: '주거금융',
    description: '저소득 무주택 가구에 전세자금 저금리 대출',
    benefits: '저금리 전세자금 대출',
    amount: '최대 1.2억원',
    eligibility: {
      incomeLevel: '연소득 5천만원 이하',
      otherRequirements: ['무주택 세대주'],
    },
    applicationMethods: ['주택도시기금', '은행'],
    requiredDocuments: ['신분증', '소득증빙', '임대차계약서'],
    processingTime: '7일 이내',
    contactInfo: '주택도시기금 1566-9009',
    tags: ['전세', '대출', '주거'],
    popularity: 82,
  },

  // 고용 (20개)
  {
    id: 'service-24',
    name: '국민취업지원제도',
    category: '고용',
    subcategory: '취업지원',
    description: '취업을 원하는 구직자에게 취업지원서비스와 소득지원 제공',
    benefits: '취업지원 프로그램, 구직촉진수당 지급',
    amount: '월 최대 50만원 (6개월)',
    eligibility: {
      ageRange: { min: 15, max: 69 },
      incomeLevel: '기준 중위소득 60% 이하 (I유형)',
    },
    applicationMethods: ['고용센터', '온라인(워크넷)'],
    requiredDocuments: ['신분증', '소득증빙'],
    processingTime: '14일 이내',
    contactInfo: '고용노동부 1350',
    tags: ['취업', '구직', '수당'],
    popularity: 88,
  },
  {
    id: 'service-25',
    name: '청년내일채움공제',
    category: '고용',
    subcategory: '청년고용',
    description: '청년 근로자의 자산형성 지원',
    benefits: '2년 근속 시 1,200만원 + 이자 수령',
    amount: '2년 만기 시 약 1,200만원',
    eligibility: {
      ageRange: { min: 15, max: 34 },
      otherRequirements: ['중소·중견기업 정규직'],
    },
    applicationMethods: ['온라인(청년내일채움공제)'],
    requiredDocuments: ['신분증', '재직증명서', '근로계약서'],
    processingTime: '30일 이내',
    contactInfo: '고용노동부 1350',
    tags: ['청년', '자산형성', '공제'],
    popularity: 85,
  },
  {
    id: 'service-26',
    name: '직업훈련',
    category: '고용',
    subcategory: '훈련지원',
    description: '구직자·재직자의 직업능력개발 훈련 지원',
    benefits: '무료 또는 저렴한 직업훈련',
    eligibility: {
      ageRange: { min: 15 },
    },
    applicationMethods: ['HRD-Net', '훈련기관'],
    requiredDocuments: ['신분증'],
    processingTime: '상시',
    contactInfo: 'HRD-Net 1544-7800',
    tags: ['훈련', '직업', '기술'],
    popularity: 80,
  },
  {
    id: 'service-27',
    name: '고용촉진장려금',
    category: '고용',
    subcategory: '고용장려',
    description: '취업 취약계층을 고용한 기업에 인건비 지원',
    benefits: '인건비 지원',
    amount: '월 최대 80만원 (최대 1년)',
    eligibility: {
      otherRequirements: ['고용보험 적용 사업장'],
    },
    applicationMethods: ['고용센터'],
    requiredDocuments: ['사업자등록증', '근로계약서'],
    processingTime: '30일 이내',
    contactInfo: '고용노동부 1350',
    tags: ['고용', '장려금', '기업'],
    popularity: 65,
  },
  {
    id: 'service-28',
    name: '실업급여',
    category: '고용',
    subcategory: '실업지원',
    description: '비자발적 실업자에게 구직활동 기간 동안 급여 지급',
    benefits: '퇴직 전 평균임금의 60% 지급',
    amount: '일 66,000원 ~ 73,000원',
    eligibility: {
      otherRequirements: ['비자발적 이직', '고용보험 가입'],
    },
    applicationMethods: ['고용센터', '온라인(워크넷)'],
    requiredDocuments: ['신분증', '이직확인서'],
    processingTime: '14일 이내',
    contactInfo: '고용노동부 1350',
    tags: ['실업', '급여', '구직'],
    popularity: 92,
  },

  // 교육 (12개)
  {
    id: 'service-29',
    name: '교육급여',
    category: '교육',
    subcategory: '기초교육',
    description: '저소득층 학생의 교육비 부담 경감',
    benefits: '교육활동지원비, 교과서비 지원',
    amount: '초등 461,000원, 중학 654,000원, 고등 727,000원 (연)',
    eligibility: {
      incomeLevel: '기준 중위소득 50% 이하',
      otherRequirements: ['초·중·고 재학생'],
    },
    applicationMethods: ['주민센터', '학교'],
    requiredDocuments: ['신분증', '소득증빙', '재학증명서'],
    processingTime: '30일 이내',
    contactInfo: '교육부 1577-0199',
    tags: ['교육', '학비', '저소득'],
    popularity: 88,
  },
  {
    id: 'service-30',
    name: '학자금대출',
    category: '교육',
    subcategory: '학자금',
    description: '대학생의 등록금 및 생활비 저금리 대출 지원',
    benefits: '저금리 학자금 대출',
    amount: '등록금 전액 + 생활비 연 400만원',
    eligibility: {
      incomeLevel: '기준 중위소득 200% 이하 (유형별 상이)',
      otherRequirements: ['대학 재학생'],
    },
    applicationMethods: ['한국장학재단'],
    requiredDocuments: ['신분증', '재학증명서', '소득증빙'],
    processingTime: '14일 이내',
    contactInfo: '한국장학재단 1599-2000',
    tags: ['학자금', '대출', '대학'],
    popularity: 90,
  },
  {
    id: 'service-31',
    name: '국가장학금',
    category: '교육',
    subcategory: '장학금',
    description: '대학생의 등록금 부담 완화를 위한 장학금 지원',
    benefits: '등록금 범위 내 장학금 지급',
    amount: '연간 최대 700만원',
    eligibility: {
      incomeLevel: '기준 중위소득 200% 이하 (구간별 차등)',
      otherRequirements: ['대학 재학생', '성적 기준 충족'],
    },
    applicationMethods: ['한국장학재단'],
    requiredDocuments: ['신분증', '재학증명서'],
    processingTime: '학기 시작 전',
    contactInfo: '한국장학재단 1599-2000',
    tags: ['장학금', '대학', '등록금'],
    popularity: 95,
  },

  // 돌봄 (20개)
  {
    id: 'service-32',
    name: '노인돌봄종합서비스',
    category: '돌봄',
    subcategory: '노인돌봄',
    description: '신체·정신적 기능 저하로 돌봄이 필요한 노인에게 가사·활동 지원',
    benefits: '가사지원, 활동지원, 주간보호 등',
    amount: '월 27~54시간 서비스',
    eligibility: {
      ageRange: { min: 65 },
      incomeLevel: '기준 중위소득 160% 이하',
      otherRequirements: ['장기요양 등급외 A, B'],
    },
    applicationMethods: ['주민센터'],
    requiredDocuments: ['신분증', '등급외 판정서'],
    processingTime: '30일 이내',
    contactInfo: '노인돌봄콜센터 1577-0199',
    tags: ['노인', '돌봄', '가사'],
    popularity: 85,
  },
  {
    id: 'service-33',
    name: '독거노인 응급안전서비스',
    category: '돌봄',
    subcategory: '응급안전',
    description: '독거노인에게 응급상황 발생 시 신속한 대응 서비스 제공',
    benefits: '응급안전장비 설치, 24시간 모니터링',
    eligibility: {
      ageRange: { min: 65 },
      householdTypes: ['1인'],
    },
    applicationMethods: ['주민센터'],
    requiredDocuments: ['신분증'],
    processingTime: '14일 이내',
    contactInfo: '독거노인종합지원센터',
    tags: ['독거노인', '응급', '안전'],
    popularity: 78,
  },
  {
    id: 'service-34',
    name: '장애인활동지원',
    category: '돌봄',
    subcategory: '장애인돌봄',
    description: '장애인에게 활동보조, 방문목욕, 방문간호 서비스 제공',
    benefits: '활동보조, 방문목욕, 방문간호 서비스',
    amount: '월 최대 480시간',
    eligibility: {
      ageRange: { min: 6, max: 64 },
      otherRequirements: ['등록 장애인', '활동지원등급 인정'],
    },
    applicationMethods: ['국민연금공단'],
    requiredDocuments: ['신분증', '장애인등록증'],
    processingTime: '30일 이내',
    contactInfo: '국민연금공단 1355',
    tags: ['장애인', '활동지원', '돌봄'],
    popularity: 82,
  },
  {
    id: 'service-35',
    name: '아이돌봄서비스',
    category: '돌봄',
    subcategory: '아동돌봄',
    description: '맞벌이 가정 등의 12세 이하 아동 돌봄 지원',
    benefits: '시간제 돌봄, 영아종일제 돌봄',
    amount: '시간당 11,630원 (정부지원 시 자부담 10~20%)',
    eligibility: {
      otherRequirements: ['12세 이하 아동', '맞벌이 등'],
    },
    applicationMethods: ['아이돌봄서비스 홈페이지'],
    requiredDocuments: ['신분증', '소득증빙'],
    processingTime: '7일 이내',
    contactInfo: '아이돌봄 1577-2514',
    tags: ['아이', '돌봄', '맞벌이'],
    popularity: 88,
  },
  {
    id: 'service-36',
    name: '가사·간병 방문지원',
    category: '돌봄',
    subcategory: '가사간병',
    description: '저소득 가구에 가사·간병 서비스를 제공하여 생활 안정 도모',
    benefits: '가사활동, 신체수발, 간병 등 서비스',
    amount: '월 24~36시간',
    eligibility: {
      incomeLevel: '기준 중위소득 70% 이하',
      otherRequirements: ['만 65세 미만 장애정도가 심한 장애인, 6개월 이상 치료 필요 등'],
    },
    applicationMethods: ['주민센터'],
    requiredDocuments: ['신분증', '소득증빙', '진단서'],
    processingTime: '30일 이내',
    contactInfo: '주민센터',
    tags: ['가사', '간병', '돌봄'],
    popularity: 70,
  },
  {
    id: 'service-37',
    name: '경로당 운영지원',
    category: '돌봄',
    subcategory: '노인복지',
    description: '경로당 운영 및 프로그램 지원',
    benefits: '경로당 운영비, 냉난방비, 프로그램 지원',
    eligibility: {
      ageRange: { min: 65 },
    },
    applicationMethods: ['경로당 방문'],
    requiredDocuments: ['신분증'],
    processingTime: '상시',
    contactInfo: '관할 구청',
    tags: ['경로당', '노인', '여가'],
    popularity: 75,
  },
];

// 카테고리별 서비스 수 통계
export const serviceStats = {
  total: welfareServices.length,
  byCategory: {
    '생활지원': welfareServices.filter(s => s.category === '생활지원').length,
    '의료': welfareServices.filter(s => s.category === '의료').length,
    '주거': welfareServices.filter(s => s.category === '주거').length,
    '고용': welfareServices.filter(s => s.category === '고용').length,
    '교육': welfareServices.filter(s => s.category === '교육').length,
    '돌봄': welfareServices.filter(s => s.category === '돌봄').length,
  } as Record<ServiceCategory, number>,
};

// 카테고리 목록
export const serviceCategories: ServiceCategory[] = ['생활지원', '의료', '주거', '고용', '교육', '돌봄'];
